# Generated by Django 4.1.3 on 2022-11-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('costo', models.CharField(max_length=50, verbose_name='costo')),
                ('asignatura', models.CharField(max_length=50, verbose_name='asignatura')),
                ('comentario', models.CharField(max_length=250, verbose_name='comentario')),
            ],
        ),
    ]
