# Generated by Django 4.0.5 on 2022-07-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lola',
            fields=[
                ('rut', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellido materno')),
                ('correos', models.EmailField(max_length=200, verbose_name='Correo')),
                ('ticket', models.CharField(max_length=200, verbose_name='Ticket')),
                ('edad', models.IntegerField()),
                ('movilidad', models.CharField(max_length=200, verbose_name='Movilidad')),
                ('fecha', models.DateField()),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
