# Generated by Django 4.1.3 on 2022-11-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_dote', '0002_rename_movilidad_lola_asignatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lola',
            name='precio',
            field=models.IntegerField(max_length=200),
        ),
    ]
