# Generated by Django 4.1.3 on 2022-11-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_dote', '0003_alter_lola_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lola',
            name='precio',
            field=models.CharField(max_length=100, verbose_name='precio'),
        ),
    ]
